# name: Checkmarx SCA Scan
 
# on:
#   push:
#     branches:
#       [main, master]
#   pull_request:
#     branches:
#       [main, master]
 
# jobs:
#   sca-scan:
#     name: Run Checkmarx AST Scan using CLI
#     runs-on: ubuntu-latest
#     env:
#       ACTIONS_RUNNER_DEBUG: true
#       ACTIONS_STEP_DEBUG: true
 
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3
 
 
#       - name: Checkmarx AST Github Action
#         uses: actions/checkout@v3
#         with:
#           base_uri: https://eu.ast.checkmarx.net
#           cx_tenant: ast_abdul_ansari
#           cx_client_id: HarshG
#           cx_client_secret: QvtZSbiAK8gBhOMe8h278R9OBT2t37xT
#           project_name: GitCICD
#           additional_params: "--report-format sbom --report-sbom-format CycloneDxJson --threshold sca-critical=100"

name: Checkmarx One Scan
on:
 push:
   branches:
     - main
     - master
     - dev
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Checkmarx One CLI Action
       uses: checkmarx/ast-github-action@main #Github Action version
       with:
         project_name: GitCICD
         cx_tenant: ast_abdul_ansari
         base_uri: https://eu.ast.checkmarx.net/
         cx_client_id: HarshG
         cx_client_secret: QvtZSbiAK8gBhOMe8h278R9OBT2t37xT
